### PR TITLE
Added openapi.yml documentation

### PR DESCRIPTION
**Pull request by Hanzik**
Not sure how or where to put the link to the documentation, so it's just as a link in Settings > API. Ideally a full swagger page would be much more nicer, but for the time being, it might be a bit of an overkill anyway.

Also... what is "hide" parameter in progress? From what I can tell, it has something to do with showing team members, but it is not quite clear to me.

### CODE REVIEW

**Comment by thaddeus** [comment]
The hide parameter is for live teams - you can "hide" someone in your team. The purpose is for if you're playing with a subset of your team temporarily, you don't want to show someone's objectives and needs who isn't there. That also generally applies to any tool consuming this information like RatScanner - you wouldn't want to show someone needing an item if they aren't currently playing with you. Basically its a soft approach instead of someone leaving/being kicked from a team constantly.

**Comment by Hanzik** [comment]
Alright, I managed to get most of it working. Live example is here: https://hanzik.github.io/TarkovTracker/ Gotta say, these GitHub pages seem like they can be pretty handy and I would definitely go this route.

1) Generating the SwaggerUI page on the go is poorly documented and seems like it's not worth the trouble. People suggest including the page as-is in the project. I placed all of its files in /docs folder - GitHub likes this folder for their "Pages".

2) Having the SwaggerUI up and available, we now only need to generate the API definition using the swagger-jsdoc. This can be done with 'npm run swagger' from the functions/ folder. This can be in the main package.json instead as I am not sure what the difference between the main one and the one in functions folder is supposed to be, but that's just a detail.

3) I moved the api.js to functions/api/v1 folder. The swagger-jsdoc needs some extra annotations for component definitions which I placed into a separate files to keep the api.js as "short" as possible. Didn't wanna throw everything into the functions folder.

**What is left now?** 
a) Setup the GitHub Pages in the main project. Settings > Pages > master + /docs. No theme needs to be selected.
b) Unless I misunderstood your second point, it feels to me like there is no need to setup anything in .github/workflows. GitHub pages read directly from the repository /docs folder, so whoever works on API or changes any of the annotations just has to run 'npm run swagger' to update the Swagger definition and push it with rest of the changes within the same commit. It *would* be nice if this was automated, but I don't see any reasonable way how you can force running 'npm run swagger' before 'git commit' :smile:

**Comment by thaddeus** [comment]
Looks great!

> This can be in the main package.json instead as I am not sure what the difference between the main one and the one in functions folder is supposed to be, but that's just a detail.

The `functions` folder in root is for Firebase functions. It's its own npm package (different dependencies from the site, and gets deployed "independent" from the site) so its split off. That being said, running scripts from root is probably ideal, so adding the script to the root `package.json` is probably preferred, but if it needs to be in the functions folder, that makese sense, the parent project can just `cd functions && npm run swagger` as part of the version script.

> a) Setup the GitHub Pages in the main project. Settings > Pages > master + /docs. No theme needs to be selected.

Sweet 👍 I love the simplicity

> b) Unless I misunderstood your second point, it feels to me like there is no need to setup anything in .github/workflows. GitHub pages read directly from the repository /docs folder, so whoever works on API or changes any of the annotations just has to run 'npm run swagger' to update the Swagger definition and push it with rest of the changes within the same commit. It _would_ be nice if this was automated, but I don't see any reasonable way how you can force running 'npm run swagger' before 'git commit' 😄

Gotchya. In that case, we could just add `npm run swagger && git commit -a -m 'Update swagger docs'` to the `npm version` script used for tagging new draft releases.

I'm happy with this either as is or with any other modifications - just pop it out of draft whenever you want me to 'review'+merge it.

**Comment by Hanzik** [comment]
Alright, I will move it to the root package.json. It can be wherever.

If you've got an automated thing for version commit, that would be an ideal place where to put it. User can do it himself in his api commit, but should he forget, this would make sure it's done either way. As some young hip kids from 90's would say here - "Supa čupa!".

**Review by thaddeus — APPROVED** [review]
👍 Looks great, thanks for another fantastic contribution!

**Pull request merged**
